url_tendencias_2linhas = "https://docs.google.com/spreadsheets/d/11pW8bTEOeKUXOb7kd53_MJwGUHG19fLWTfHvpIYVUIY/edit#gid=0"
url_tendencias_2gols = "https://docs.google.com/spreadsheets/d/17YiO2vWLU2iM8DHG7bFWI8VjKcx_aOqeww6bjvJOMRs/edit#gid=1561702516"
url_entradas_2linhas= "https://docs.google.com/spreadsheets/d/1GAfimoAgPbBv356AQnAPDz731BCZYFkA-kwXPMekWfE/edit#gid=0"
url_entradas_2gols = "https://docs.google.com/spreadsheets/d/1GAfimoAgPbBv356AQnAPDz731BCZYFkA-kwXPMekWfE/edit#gid=218119755"
url_entradas_anytime = "https://docs.google.com/spreadsheets/d/1GAfimoAgPbBv356AQnAPDz731BCZYFkA-kwXPMekWfE/edit#gid=1293114692"
url_entradas_semmetodo = "https://docs.google.com/spreadsheets/d/1GAfimoAgPbBv356AQnAPDz731BCZYFkA-kwXPMekWfE/edit#gid=1251942649"
url_jogador = "https://docs.google.com/spreadsheets/d/1yEC57lEM9R36ZQ3ZHpLgiGgLyFvCTLMxh9m6pvF40xE/edit?usp=sharing"
