url_tendencias_2linhas = "https://docs.google.com/spreadsheets/d/11pW8bTEOeKUXOb7kd53_MJwGUHG19fLWTfHvpIYVUIY/edit#gid=0"
url_tendencias_2gols = "https://docs.google.com/spreadsheets/d/17YiO2vWLU2iM8DHG7bFWI8VjKcx_aOqeww6bjvJOMRs/edit#gid=1561702516"
